[package]
name = "jay"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[workspace]
members = ["jay-config", "default-config", "algorithms"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
uapi = "0.2.10"
thiserror = "1.0.30"
ahash = "0.8.2"
log = { version = "0.4.16", features = ["std"] }
futures-util = "0.3.19"
num-traits = "0.2.14"
num-derive = "0.4.1"
bitflags = "2.4.1"
libloading = "0.8.1"
bstr = { version = "1.1.0", default-features = false, features = ["std"] }
isnt = "0.1.0"
once_cell = "1.9.0"
rand = "0.8.4"
smallvec = { version = "1.8.0", features = ["const_generics", "const_new", "union"] }
byteorder = "1.4.3"
bincode = "2.0.0-rc.1"
jay-config = { path = "jay-config" }
default-config = { path = "default-config" }
algorithms = { path = "algorithms" }
pin-project = "1.0.10"
clap = { version = "4.0.29", features = ["derive", "wrap_help"] }
clap_complete = "4.0.6"
humantime = "2.1.0"
dirs = "5.0.1"
backtrace = "0.3.64"
chrono = "0.4.19"
parking_lot = "0.12.1"
arrayvec = "0.7.4"

[build-dependencies]
repc = "0.1.1"
anyhow = "1.0.52"
bstr = { version = "1.1.0", default-features = false, features = ["std"] }

#[profile.dev.build-override]
#opt-level = 3

[profile.dev.package."algorithms"]
opt-level = 3

[profile.dev.package."smallvec"]
opt-level = 3

[features]
rc_tracking = []
it = []
