[package]
name = "jay-algorithms"
version = "0.4.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Internal dependency of the Jay compositor"
repository = "https://github.com/mahkoh/jay"

[dependencies]
smallvec = { version = "1.8.0", features = ["const_generics", "const_new", "union"] }
